# Generated by Django 4.2.6 on 2023-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('destinos', models.ManyToManyField(to='destinos.destino')),
            ],
        ),
    ]
