# Generated by Django 4.2.6 on 2023-11-12 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinos', '0003_remove_destino_empresa_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roteiro',
            old_name='destinos',
            new_name='Destinos',
        ),
        migrations.RenameField(
            model_name='roteiro',
            old_name='name',
            new_name='Nome',
        ),
        migrations.AlterField(
            model_name='roteiro',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
