# Generated by Django 4.2.6 on 2023-11-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0004_rename_destinos_roteiro_destinos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roteiro',
            old_name='author',
            new_name='autor',
        ),
    ]
