# Generated by Django 4.2.6 on 2023-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0005_rename_author_roteiro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='Capa',
            field=models.URLField(max_length=5000, null=True),
        ),
    ]
