# Generated by Django 4.2.6 on 2023-11-12 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinos', '0006_roteiro_capa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roteiro',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='list',
        ),
    ]
