# Generated by Django 4.2.7 on 2023-11-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0007_rename_roteiro_list_rename_movie_review_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='destinos',
            new_name='atracoes',
        ),
    ]
